#+title: COV-IN-CLI

The Corona pandemic is on everyone's mind. There are many shiny GUI's available to visualize the
COVID19-India Data. Thanks to all of them.

On other note " I know nothing about epidemiology."

The data source for my tool is https://api.covid19india.org/. A big shout out to all the developers
for there amazing dedication and bring us the formated data and GUI.


* COV-IN-CLI

A CLI written in Python3 to get the Covid19-India data.


*** Prerequisite

  - You need nothing more than a basic installation of Python 3.6 or newer and time to work on it.
  - Virtualenv

Follow below step to install and setup the Python Virtual Env

#+begin_src
sudo pip3 install virtualenv
python3 -m venv covid19
source covid19/bin/activate
pip3 install -r requirements.txt
#+end_src


*** Goal

An attempt to create a 1st COVID-19 India CLI.


*** Currently tool support 7 subcommands

     - country
     - district
     - state
     - state-cases
     - district-cases
     - states-name
     - districts-name

Note:

     - The CLI is still WIP and the arguments may change over the period of time.
     - This is a fun project for me.
     - I am not Python expert

** Run CLI

*** Country(country)

Accepts 1 flag at a time

 - active
 - confirmed
 - deceased
 - recovered

#+begin_src
❯ covid19/bin/python3 covid.py country -a confirmed
Total confirmed cases in India are : 336370

❯ covid19/bin/python3 covid.py country -a active
Total active cases in India are : 154144

❯ covid19/bin/python3 covid.py country -a recovered
Total recovered cases in India are : 172578

❯ covid19/bin/python3 covid.py country -a deceased
Total deceased cases in India are : 9597
#+end_src

*** State(state)

Command state accepts 2 flags

 - statename
  &&
 - active
 - confirmed
 - deceased
 - recovered

Note:- To get Indian States and Union Territories names please refer below Wiki

[[https://en.wikipedia.org/wiki/States_and_union_territories_of_India][Indian State and Union Territories]]

or you can run a CLI itself to get Indian States and Union Territories names

#+BEGIN_SRC
covid19/bin/python3 covid.py states-name

India's States and Union Territories Names are:
<--******************************************-->
['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Delhi', 'Dadra and Nagar Haveli and Daman and Diu', 'Goa', 'Gujarat', 'Himachal Pradesh', 'Haryana', 'Jharkhand', 'Jammu and Kashmir', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Maharashtra', 'Meghalaya', 'Manipur', 'Madhya Pradesh', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Puducherry', 'Rajasthan', 'Sikkim', 'Telangana', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']
#+END_SRC


#+BEGIN_SRC
❯ covid19/bin/python3 covid.py state 'Madhya Pradesh' -a confirmed
Total confirmed cases in Madhya Pradesh are: 10935

❯ covid19/bin/python3 covid.py state 'Madhya Pradesh' -a active
Total active cases in Madhya Pradesh are: 2567

❯ covid19/bin/python3 covid.py state 'Madhya Pradesh' -a recovered
Total recovered cases in Madhya Pradesh are: 7903

❯ covid19/bin/python3 covid.py state 'Madhya Pradesh' -a deceased
Total deceased cases in Madhya Pradesh are: 465
#+END_SRC
